In [5]:
import numpy as np
import matplotlib.pyplot as plt

# Problem Statement
Size (sqft)	Number of Bedrooms	Number of floors	Age of Home	Price (1000s dollars)
2104	5	1	45	460
1416	3	2	40	232
852	    2   1	35	178


Creating arrays for X_train and Y_train

In [6]:
X_train = np.array([
    [2104, 5, 1, 45],
    [1416, 3, 2, 40],
    [852 , 2, 1, 35]
    ],
    dtype= np.dtype(float)
)

Y_train = np.array([460, 232, 178], dtype=np.dtype(float))

Printing shape and matrices

In [7]:
print(f"Shape of X_train : {np.shape(X_train)}")
print("X_train : \n", X_train)
print(f"Shape of Y_train : {np.shape(Y_train)}")
print("Y_train : \n" , Y_train)

Shape of X_train : (3, 4)
X_train : 
 [[2.104e+03 5.000e+00 1.000e+00 4.500e+01]
 [1.416e+03 3.000e+00 2.000e+00 4.000e+01]
 [8.520e+02 2.000e+00 1.000e+00 3.500e+01]]
Shape of Y_train : (3,)
Y_train : 
 [460. 232. 178.]


Parameter vector w, b

In [8]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])

print(f"The type of b_init : {type(b_init)}")
print(f"The type of w_init : {type(w_init)}")
print(f"The shape of w_init : {np.shape(w_init)}")

The type of b_init : <class 'float'>
The type of w_init : <class 'numpy.ndarray'>
The shape of w_init : (4,)


In [9]:
print(X_train.shape[0]) # gives no. of elements of X_train


3


Function:
    single predict using linear regression    
    Args:
      x (ndarray): Shape (n,) example with multiple features
      w (ndarray): Shape (n,) model parameters    
      b (scalar):  model parameter     
      

In [10]:
def predicted_single_loop(x , w, b):

    # no. of samples:
    no_of_training_examples = x.shape[0]

    #prediction:
    y_hat = 0

    for example in range(no_of_training_examples):
        # y = wx + b
        i_prediction = w[example] * x[example]
        y_hat = y_hat + i_prediction
    # After iterating all training examples and multiplied them with w, add bias
    y_hat = y_hat + b
    return y_hat


# get a row from our training data

X_train[0, :2] 
here :
0 indicates the first element of X_train, it means row 1.
,
: indicatess the column of that first element. here : indicates all the columns.

e.g:

[0, :2] : first row, first 2 columns of that row
[0, :] : first row , all columns of that row.

In [11]:
X_example = X_train[0, :]
print(f"First training example is : {X_example}, and its shape is : {X_example.shape}")

First training example is : [2.104e+03 5.000e+00 1.000e+00 4.500e+01], and its shape is : (4,)


# make a prediction
Now we have x , w, b

x = X_example
w = w_init
b = b_init

So, now we will use them, and make prediction

In [12]:
f_wb = predicted_single_loop(X_example, w_init, b_init)
print(f"The price of house with {X_example[0] } sqft size, {X_example[1]} bedrooms, {X_example[2]} floors and with age of {X_example[3]} is: {f_wb}.")

The price of house with 2104.0 sqft size, 5.0 bedrooms, 1.0 floors and with age of 45.0 is: 459.9999976194083.


# Compute Cost With Multiple Variables

The equation for the cost function with multiple variables  𝐽(𝐰,𝑏)
  is:
𝐽(𝐰,𝑏)=1/2𝑚 ∑𝑖=0 𝑚−1 (𝑓𝐰,𝑏(𝐱(𝑖))−𝑦(𝑖))2

In [13]:
def compute_cost(x,y,w,b):
    m = x.shape[0] # m is total no. of samples
    cost = 0
    for i in range(m):
        f_wb_i = np.dot(x[i],w) + b # as we know, f w,b(x) = wx + b. so, we are first calculating this f_wb for each element m.
        # once f w,b (x) is calculated, 
        # next
        # put it in j(w, b) = 1/2m  ∑𝑖=0 𝑚−1  (f w,b(x) - y)^2
        # f w,b(x) replce it with f_wb_i
        # 
        cost = cost + (f_wb_i - y[i])**2 

    # so , now ∑𝑖=0 𝑚−1  (f w,b(x) - y)^2 is calculated , once its done, we have to multiply the cost by 1/2m
    cost = cost / (2*m)
    return cost


In [14]:
cost_cal = compute_cost(X_train, Y_train, w_init, b_init)
print(f"The optimal w cost : {cost_cal}")

The optimal w cost : 1.5578904428966628e-12


# no. of sample , and  no. of feature in each sample

In [20]:
m,n = X_train.shape # this gives no. of sample , and  no. of feature in each sample
print(m)
print(n)

3
4
