In [2]:
import numpy as np
import time

Vector Creation

In [6]:
a1 = np.arange(4.)
print(a1)
print(f"Type : {type(a1)}")
print(f"Shape : {a1.shape}")

[0. 1. 2. 3.]
Type : <class 'numpy.ndarray'>
Shape : (4,)


Indexing

In [8]:
b1 = a1[2]
print(b1)

2.0


Slicing

In [9]:
c1 = a1[1:3]
print(c1)

[1. 2.]


Vector Vector element-wise operations

In [12]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = a + b
print(f"a + b = {c}")

a + b = [ 6  8 10 12]


When performing these operations, both the arrays should have same number of elements.
If the len is not same, it throws an error.

In [14]:
a4 = np.array([1,2,3,4])
b4 = np.array([5,6,8])

try:
    c = a4 + b4
    print(f"a + b = {c}")
except Exception as err:
    print(err)

operands could not be broadcast together with shapes (4,) (3,) 


# Scalar Vector operations
Vector can be scaled by a scaler: means that every element of a vector can be multiplied with a scaler number.

In [16]:
a5 = np.array([6,7,8,9])
b5 = a5 * 5
print(f"The result of a5 * 5 : {b5}")

The result of a5 * 5 : [30 35 40 45]


Vector Vector dot product
The dimentions of two vectores should be same for dot product.

In [ ]:
def dot_product(a,b):
    x = 0
    for i in range(a.shape[0]): # a.shape[0] gives an integer value of number of rows, so loop can iterate. where a.shape returns a tuple on which loop can't iterate.
        x = x + a[i] * b[i]
    return x

In [18]:
a_ = np.array([
    [1,2,3],
    [4,5,6]
])

b_ = np.array([
    [6,7,8],
    [3,6,0]
])

In [19]:
c_ = dot_product(a_ , b_)
print(c_)

[18 44 24]


In [20]:
#Using 1D array
a_1 = np.array([1,6,8,0,5])
b_1 = np.array([3,4,6,8,1])
c_1 = dot_product(a_1 , b_1)
print(c_1)

80


The Need for Speed: vector vs for loop

In [21]:
print(time.time())

1755747062.5835083


In [28]:
np.random.seed(1)
A = np.random.rand(10000000)
B = np.random.rand(10000000)

# Using dot Product
tic = time.time() # start time
C = np.dot(A, B)  # dot product of A and B
toc = time.time() # end time

print(f"dot(A, B) = {C:.4f}")
print(f"Time using vectorization : {1000 * (toc-tic):.4f} ms")


#Using for loop
tic2 = time.time() # start
C2 = dot_product(A , B)   # dot product using for loop
toc2 = time.time()

print(f"Using for loop : {C2:.4f}")
print(f"Time using for loop is : {1000 * (toc2-tic2):.4f} ms")

dot(A, B) = 2501072.5817
Time using vectorization : 12.8953 ms
Using for loop : 2501072.5817
Time using for loop is : 4610.8997 ms


In [ ]:
#vector 2-D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")

#access 5 consecutive elements (start:stop:step)
print("a[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")

#access 5 consecutive elements (start:stop:step) in two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)

# access all elements in one row (very common usage)
print("a[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")
# same as
print("a[1]   = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)
a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array
a[1]   =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array
