In [1]:
import numpy as np

In [2]:
a = np.zeros(4)
print(a.shape)

(4,)


In [3]:
print(a.dtype)

float64


In [4]:
b = np.array([1,2,3,4])
print(b)
print(b.shape)
print(b.dtype)

[1 2 3 4]
(4,)
int64


In [12]:
c = np .array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(c)
print(c.dtype)
print(c.shape)
print(c[2].shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)
(3,)


In [6]:
d = np.random.random_sample(4)
print(d)
print(d.dtype)
print(d.shape)

[0.09132948 0.25636381 0.37964123 0.33841299]
float64
(4,)


In [7]:
e = np.random.rand(4)
print(e)
print(e.dtype)
print(e.shape)

[0.54804211 0.90380766 0.52100556 0.30163518]
float64
(4,)


In [8]:
f = np.arange(5)
print(f)
print(f.dtype)
print(f.shape)

[0 1 2 3 4]
int64
(5,)


In [9]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
print(a[2].shape)
# bcz, s[2] is a scaler number and when we index 1d array with single int , we get a scaler.
# a sclaer is a single value of any type. int may be a scaler. but every scaler is not int.

()


In [13]:
try:
  print(a[10])
except Exception as e:
  print("There is an error: ", e)


There is an error:  index 10 is out of bounds for axis 0 with size 10


In [18]:
# Slicing

print(a[2:8])
print(a[2:8:2])
print(a[:3])
print(a[3:])
print(a[-1])
print(a[:])

[2 3 4 5 6 7]
[2 4 6]
[0 1 2]
[3 4 5 6 7 8 9]
9
[0 1 2 3 4 5 6 7 8 9]


In [19]:
m = -a
print(f"m: {m}")
print(f"a: {a}")

m: [ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
a: [0 1 2 3 4 5 6 7 8 9]


In [21]:
# Functions

print(sum(a))
print(sum(m))

print(np.mean(a))
print(np.mean(m))

45
-45
4.5
-4.5


In [22]:
print(a ** 2)

[ 0  1  4  9 16 25 36 49 64 81]


In [24]:
a = np.array([1, 3, 4, 6])
b = np.array([1,-3, -5, -3])

print(a + b)

# for this operation, the vectors must be of same size.

[ 2  0 -1  3]


In [26]:
# with different vector sizes

a = np.array([1,2,3,4])
b = np.array([1,2,3])

try:
  print(a + b)
except Exception as e:
  print(f"The error message you will get is: {e}")

The error message you will get is: operands could not be broadcast together with shapes (4,) (3,) 


Scalar Vector Operations

In [28]:
a = np.array([1,2,3,4])
b = 5 * a

print(a)
print(b)

[1 2 3 4]
[ 5 10 15 20]


In [29]:
# Dot product
a = np.array([1,2,3,4])
b = np.array([1,2,5,7])

def dot_product(x, y):
  dot_p = 0
  m = x.shape[0]
  for i in range(m):
    xy_i = x[i] * y[i]
    dot_p += xy_i
  return dot_p


cal_dot = dot_product(a,b)
print(cal_dot)


48


In [32]:
# using numpy dot() function
a = np.array([1,-2,3,4])
b = np.array([1,2,5,7])

c = np.dot(a,b)
print(c)
print(c.shape) # it will show () bcz, its a scalar

d = np.dot(b,a)
print(d)

40
()
40


In [35]:
np.random.seed(1)
a = np.random.rand(10)
print(a)

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [36]:
import time

In [51]:
print("%%%%% Loop Version %%%%%")
print(" ")

a = np.array([1,-2,3,4])
b = np.array([1,2,5,7])
tic = time.time()
loop_results = dot_product(a,b)
print(f"Dot product result using loop: {loop_results}")
toc = time.time()
print(f"Start time: {tic:.4f} , Stop Time: {toc:.4f}")
time_stamp = toc-tic
print(f"Loop version duration: {1000 * time_stamp:.4f}ms")

print(" ")
print("%%%%% dot() Function Version %%%%%")
print(" ")

# now lets do the dot product by numpy dot function
tic = time.time()
fun_result = np.dot(a,b)
print(f"Dot Product Computeed by np.dot() function: {fun_result}")
toc = time.time()
print(f"Start Time before np.dot(): {tic:.4f} , End Time: {toc:.4f}")
print(f"np.dot() function Duration: {1000 * (toc-tic):.4f}ms")

%%%%% Loop Version %%%%%
 
Dot product result using loop: 40
Start time: 1786800625.3586 , Stop Time: 1786800625.3587
Loop version duration: 0.0887ms
 
%%%%% dot() Function Version %%%%%
 
Dot Product Computeed by np.dot() function: 40
Start Time before np.dot(): 1786800625.3589 , End Time: 1786800625.3590
np.dot() function Duration: 0.1349ms


In [53]:
x = np.array([
    [1],
    [2],
    [3],
    [4]
])

a = x[1]
w = np.array([2])


print(x.shape)
result = np.dot(a, w)
print(result)
print(result.shape)
print(a.shape)
print(w.shape)

# so, both a and w returns (1,) not () , bcz both are vectors not scalar, the result is a computation of dot product and its a scalar value, so it reurns ().
# (1,) is a one dimensional array having 1 element
# () is a 0 dimentional array, its a scalar.


(4, 1)
4
()
(1,)
(1,)


In [59]:
a = np.array([[1,2], [3,2]])
b = np.array([1, 2])

print(a)
print(b)

print(a.shape)
print(b.shape)


print(a.dtype)
print(b.dtype)

print(type(a))
print(type(b))

[[1 2]
 [3 2]]
[1 2]
(2, 2)
(2,)
int64
int64
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Matrix

In [61]:
import numpy as np

In [68]:
a = np.zeros((1,2))
print(a)
print(a.shape)

b = np.zeros((4, 5))
print(b)
print(b.shape)

c = np.random.random_sample((3,4))
print(c)
print(c.shape)

[[0. 0.]]
(1, 2)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(4, 5)
[[0.87811744 0.02738759 0.67046751 0.4173048 ]
 [0.55868983 0.14038694 0.19810149 0.80074457]
 [0.96826158 0.31342418 0.69232262 0.87638915]]
(3, 4)


In [69]:
a = np.arange(6).reshape(-1, 2)       # the reshape(-1,2) means, there should be 2 columns, and the remaining will be rows, range of 6: 2 * 3 = 6 ,so 2 rows and 3 columns
print(a)
print(a.shape)




[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [70]:
# indexing in matrix

print(a[2,1])  # it returns the scalar, in index 2, the row is 3,  [4 5], then column index 1, the column is 2, so , the targeted value is 5.
print(a[2,1].shape) # will return () , coz , its a scalar
print(a[2])   # now we have not specified the clumn, we only provide 1 value , that is for row, so index 2 is row 3. it will give [4,5]
print(a[2].shape) # now its 1D array, it will give (2,)

5
()
[4 5]
(2,)


Slicing

In [75]:
a = np.arange(20).reshape(-1, 10)
print(a)
print(a.shape)


print(a[0, 2:8])
print(a[0, 2:9:2])

print(a[0, 2:8].shape)
print(a[0, 2:9:2].shape)


print(a[1, 1:7:3])
print(a[1, 0:7:3])

print(a[1, 1:7:3].shape)
print(a[1, 0:7:3].shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)
[2 3 4 5 6 7]
[2 4 6 8]
(6,)
(4,)
[11 14]
[10 13 16]
(2,)
(3,)


In [76]:
print(a[: , :])
print(a[: , :].shape)


print(a[1])
print(a[1].shape)

print(a[1 , :])
print(a[1 , :].shape)

print(a[: , 1])
print(a[: , 1].shape)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)
[10 11 12 13 14 15 16 17 18 19]
(10,)
[10 11 12 13 14 15 16 17 18 19]
(10,)
[ 1 11]
(2,)


In [79]:
print(a[-1, -1])
print(a[-1, -1].shape)

19
()


In [78]:
print(a[-1])
print(a[-1].shape)

[10 11 12 13 14 15 16 17 18 19]
(10,)
